---
title: "R Notebook"
output: html_notebook
---


```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(dplyr))
```


```{r}
posts <- read.csv("wallstreetbets_posts.csv")
comments <- read.csv("wallstreetbets_comments.csv")
```
           
```{r}
posts %>% 
  ggplot() +
    geom_histogram(mapping = aes(x = created_utc), bins = 100)

```

```{r}
posts <- posts %>%
  select(title,
         created_utc, 
         author, 
         num_crossposts,
         num_comments,
         upvote_ratio,
         selftext
  )
```


CONVERTING TO DATE FROM EPOCH
er

```{r}
posts2 <- posts %>%
  mutate('datetime' = as.POSIXct(created_utc, origin = "1970-01-01"),
         'dates' = as.Date(created_utc, origin = "1970-01-01")
  )

```


```{r}
posts2 <- posts2 %>%
  order(created_utc)
```

```{r}
posts2 %>%
  ggplot() +
  geom_histogram(mapping = aes(x = dates))
```

